/*
 * File: app/view/DebtListItem.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.DebtListItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.DebtListItem',

    requires: [
        'Ext.Container',
        'Ext.XTemplate',
        'Ext.Button'
    ],

    config: {
        height: 64,
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                cls: 'loanshark-item-container',
                itemId: 'debtListItemDetail',
                tpl: [
                    '<div class="debt-list-item-detail">',
                    '    <div class="debt-balance">',
                    '        {[(values.balance <= 0)?\'Paid Off\':(\'$ \' + values.balance.toFixed(2))]}',
                    '    </div>',
                    '    <div class="debt-date-name">',
                    '        Owed by {[Ext.getStore(\'PeopleStore\').getById(values.person_id).get(\'name\');]} since {[(values.date.getMonth()+1) + \'/\' + values.date.getDate() + \'/\' + values.date.getFullYear()]}',
                    '    </div>',
                    '    ',
                    '</div>'
                ],
                items: [
                    {
                        xtype: 'button',
                        cls: 'loanshark-item-delete-button',
                        docked: 'right',
                        hidden: true,
                        hideAnimation: 'popOut',
                        itemId: 'deleteDebt',
                        showAnimation: 'pop',
                        iconCls: 'icon-delete'
                    }
                ]
            }
        ]
    },

    updateRecord: function(record) {
        var debtDetail = this.child('#debtListItemDetail');
        var deleteDebtButton = debtDetail.child('#deleteDebt');
        //put the data in the tpl
        debtDetail.setData(record.data);
        //add record reference to the button
        deleteDebtButton.setData(record);
    },

    showDeleteButton: function() {
        this.down('button#deleteDebt').show();
    },

    hideDeleteButton: function() {
        this.down('button#deleteDebt').hide();
    }

});