/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.MainView', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Payback.view.Summary',
        'Payback.view.Contacts',
        'Payback.view.Debts',
        'Ext.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        id: 'MainView',
        hideAnimation: {
            type: 'slideOut',
            direction: 'left'
        },
        showAnimation: {
            type: 'slide',
            direction: 'right'
        },
        items: [
            {
                xtype: 'Summary',
                tab: {
                    iconCls: 'icon-home',
                    iconAlign: 'center',
                    flex: 1,
                    baseCls: 'x-button',
                    cls: 'main-tab'
                },
                itemId: 'Summary',
                title: 'Summary'
            },
            {
                xtype: 'Contacts',
                tab: {
                    iconCls: 'icon-contacts',
                    iconAlign: 'center',
                    flex: 1,
                    baseCls: 'x-button',
                    cls: 'main-tab'
                },
                itemId: 'Contacts',
                title: 'Contacts'
            },
            {
                xtype: 'Debts',
                tab: {
                    iconCls: 'icon-debt',
                    iconAlign: 'center',
                    flex: 1,
                    baseCls: 'x-button',
                    cls: 'main-tab'
                },
                itemId: 'Debts',
                title: 'Debts'
            }
        ],
        tabBar: {
            cls: 'loanshark-main-tab',
            docked: 'top',
            ui: 'light',
            layout: {
                type: 'hbox',
                align: 'stretchmax'
            }
        }
    }

});