/*
 * File: app/view/PaymentDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.PaymentDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.PaymentDetail',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.Number',
        'Ext.field.Hidden',
        'Ext.Toolbar',
        'Ext.Spacer'
    ],

    config: {
        hidden: true,
        id: 'PaymentDetail',
        autoDestroy: false,
        layout: 'vbox',
        hideAnimation: {
            type: 'slideOut',
            direction: 'right'
        },
        showAnimation: {
            type: 'slide',
            direction: 'left'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                ui: 'light',
                title: 'Payment Details',
                items: [
                    {
                        xtype: 'button',
                        id: 'cancelPayment',
                        iconCls: 'icon-back'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        labelAlign: 'top',
                        name: 'date',
                        value: {
                            day: new Date().getDate(),
                            month: new Date().getMonth(),
                            year: new Date().getFullYear()
                        }
                    },
                    {
                        xtype: 'numberfield',
                        label: 'Amount',
                        labelAlign: 'top',
                        name: 'amount'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Note',
                        labelAlign: 'top',
                        name: 'note'
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'debt_id'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'savePayment',
                        iconCls: 'icon-save'
                    }
                ]
            }
        ]
    }

});