/*
 * File: app/controller/Summary.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.controller.Summary', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'Summary'
        ],

        refs: {
            summaryContents: '#summaryContents'
        }
    },

    launch: function() {
        //set up a listener so the summary is updated every time that the store is updated
        Ext.getStore('PeopleStore').on('load', function(){
            this.updateSummaryContents();
        }, this);

        //and update summary right now
        this.updateSummaryContents();

    },

    updateSummaryContents: function() {
        //calculate total debt
        var totalDebt = Ext.getStore('PeopleStore').sum('balance');

        //update template data
        this.getSummaryContents().setData({
            'totalDebt':totalDebt
        });
    }

});